---
# tasks file for vmtemplate
- name: Set timezone.
  ansible.builtin.timezone:
    name: "{{ vmtemplate_timezone }}"

- name: Install guest tools.
  ansible.builtin.include_tasks:
    file: "guest-util/{{ ansible_virtualization_type | lower }}.yml"
  when: ansible_virtualization_role == "guest"

- name: "Set generic hostname."
  ansible.builtin.hostname:
    name: localhost.localdomain
  when: ansible_virtualization_type != 'docker' # We can't change hostname of a running docker container (molecule)

- name: Delete the ansible_user.
  ansible.builtin.include_tasks:
    file: user-deletion.yml

- name: Generate root password if not provided.
  ansible.builtin.set_fact:
    vmtemplate_root_pass: "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_letters length=32') }}"
  when: vmtemplate_root_pass is not defined or vmtemplate_root_pass == ''
  no_log: true

- name: Set root password.
  ansible.builtin.user:
    name: "root"
    password: "{{ vmtemplate_root_pass }}"
  no_log: true

- name: Unconfigure Guest
  ansible.builtin.include_tasks:
    file: "{{ ansible_os_family | lower }}.yml"

- name: Shutdown guest.
  community.general.shutdown:
  when: ansible_virtualization_type != 'docker' # We shouldn't shutdown a docker container from within.