---
- name: Enable ssh root login.
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: PermitRootLogin yes
    regexp: ^PermitRootLogin
  notify: restart sshd

- name: Flush handlers.
  ansible.builtin.meta: flush_handlers

- name: Switch to the root user.
  ansible.builtin.set_fact:
    previous_ssh_user: "{{ ansible_user | default(ansible_facts.user_id) }}"
    ansible_ssh_user: root
    ansible_user: root

- name: Reboot host
  ansible.builtin.reboot:

- name: Print previous_ssh_user
  ansible.builtin.debug:
    var: previous_ssh_user

- name: Delete user {{ previous_ssh_user }}.
  ansible.builtin.user:
    name: "{{ previous_ssh_user }}"
    state: absent
  when: previous_ssh_user != 'root'

- name: "Delete user home /home/{{ previous_ssh_user }}."
  ansible.builtin.file:
    path: "/home/{{ previous_ssh_user }}"
    state: absent

- name: Disable ssh root login.
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: PermitRootLogin no
    regexp: ^PermitRootLogin
